app = "telegram-rushmeta-bot"

kill_signal = "SIGINT"
kill_timeout = 5
processes = ["app"]

[build]
  dockerfile = "Dockerfile"
  [build.args]
    NODE_ENV = "production"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = "8080"
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.ports]]
  handlers = ["http"]
  port = 80
  force_https = true

[[http_service.ports]]
  handlers = ["tls", "http"]
  port = 443

[checks]
  [checks.health]
    port = 8080
    type = "http"
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "get"
    path = "/health"
