name: Deploy to Fly.io
on:
  push:
    branches: [main]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP_NAME: ${{ secrets.FLY_APP_NAME }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Create Fly App if not exists
        run: flyctl apps create ${{ env.FLY_APP_NAME }} --machines || true

      - name: Create fly.toml
        run: |
          cat > fly.toml << EOL
          app = "${{ env.FLY_APP_NAME }}"
          primary_region = "lax"
          kill_timeout = "5s"

          [build]
            dockerfile = "Dockerfile"

          [env]
            PORT = "8080"
            NODE_ENV = "production"

          [http_service]
            internal_port = 8080
            force_https = true
            auto_stop_machines = true
            auto_start_machines = true
            min_machines_running = 0
            processes = ["app"]

          [[services.ports]]
            handlers = ["http"]
            port = 80
            force_https = true

          [[services.ports]]
            handlers = ["tls", "http"]
            port = 443

          [checks]
            [checks.health]
              port = 8080
              type = "http"
              interval = "30s"
              timeout = "5s"
              grace_period = "10s"
              method = "get"
              path = "/health"
          EOL

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
